version: '3.3'
services:
  app:
    build: .
    container_name: lamden_block_service
    network_mode: "host"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /root:/root
